- name : Creating the ec2 instance and R53 update
  hosts : local
  connection : local
  vars:
    ami_id : ami-09c813fb71547fc4f
    sg_id : sg-088654339372a0863
    zone_id : Z013386211R3NLCB52I8R
    domain_name : arunenjali.fun
    region: us-east-1 
    instances :
    - mongodb
  tasks :
  - name : Creating the ec2 instance
    amazon.aws.ec2_instance:
      name : "{{item}}"
      instance_type : t3.micro
      security_group : "{{sg_id}}"
      image_id : "{{ami_id}}"
      region: "{{region}}" 
      tags :
        name : "{{item}}"
    loop : "{{instances}}"
    register : ec2_output
  
  # - name : printing the ec2_instance output
  #   ansible.builtin.debug :
  #     msg : "{{ec2_output}}"

  # - name : printing the public ip address
  #   ansible.builtin.debug :
  #     msg : "{{item.instances[0].public_ip_address}}"
  #   loop : "{{ec2_output.results}}"

  # - name : printing the private ip address
  #   ansible.builtin.debug :
  #     msg : "{{item.instances[0].private_ip_address}}"
  #   loop : "{{ec2_output.results}}"

  - name: Adding the R53 record
    amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "{{item.item}}.{{domain_name}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      overwrite : true
    loop : "{{ec2_output.results}}"
  