- name : Creating the ec2 instance and R53 update
  hosts : local
  connection : local
  become : yes
  vars:
    ami_id : ami-09c813fb71547fc4f
    sg_id : sg-088654339372a0863
    zone_id : Z013386211R3NLCB52I8R
    domain_name : arunenjali.fun
  instances :
    - mongodb

  tasks :
  - name : Creating the ec2 instance
    amazon.aws.ec2_instance:
      name : "{{item}}"
      instance_type : t3.micro
      secuirty_group : "{{sg_id}}"
      image_id : "{{ami_id}}"
      tags :
        environment : "{{item}}"
    loop : "{{instance}}"
    register : ec2_output
  
  - name : printing the ec2_instance
    ansible.builtin.debug :
      msg : "{{ec2_output}}"